# Generated by Django 4.2.20 on 2025-03-31 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('article_type', models.CharField(choices=[('article', '技术文章'), ('story', '原创故事')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
